---
- name: Update apt cache and dist-upgrade all homelab hosts
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Dist-upgrade packages
      ansible.builtin.apt:
        upgrade: dist
        autoremove: true
        autoclean: true
